language: python
python:
  - "3.5"
install:
  - pip install coveralls tox
script:
  - tox
env:  # generate list with: $ tox -l | sort | xargs -I ITEM echo "  - TOXENV="ITEM
    - TOXENV=py27-django17
    - TOXENV=py27-django18
    - TOXENV=py27-django19
    - TOXENV=py32-django17
    - TOXENV=py33-django17
    - TOXENV=py33-django18
    - TOXENV=py34-django17
    - TOXENV=py34-django18
    - TOXENV=py34-django19
    - TOXENV=py35-django18
    - TOXENV=py35-django19
