language: python
python: "3.5"
install:
  # continue to support Python 3.2 (see issue #84)
  - pip install pip==7.1.2
  - pip install coveralls tox
script:
  - tox
# NOTE: To generate (update) the env list run
# $ tox -l | sort | xargs -I ITEM echo "  - TOXENV="ITEM
env:
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py32-django17
  - TOXENV=py32-django18
  - TOXENV=py33-django17
  - TOXENV=py33-django18
  - TOXENV=py34-django17
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py35-django18
  - TOXENV=py35-django19
