language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11
matrix:
  exclude:
    # Django 1.7 does not support Python 3.5+
    - { python: 3.5, env: DJANGO=1.7 }
    - { python: 3.6, env: DJANGO=1.7 }
    # Django 1.9+ does not support Python 3.3
    - { python: 3.3, env: DJANGO=1.9 }
    - { python: 3.3, env: DJANGO=1.10 }
    - { python: 3.3, env: DJANGO=1.11 }
  include:
    - { python: 2.7, env: TOXENV=flake8 }

install:
  - pip install tox-travis
script:
  - tox
